# Generated by Django 4.1.2 on 2022-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
