# Generated by Django 4.1.2 on 2022-11-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_operation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="slackUsername",
        ),
    ]
